### ISSUE TITLE
TMNT 2 не поиграть

### ISSUE THREAD

**Issue by onuff** [grayver/mi-vigem#9]
В новых черепашках ниндзя определяется два игрока.с 1 го джойстика. Если 2 то 4 , и клавиатура не убирается.

**Comment by grayver** [comment]
Mi-ViGEm не подменяет реальный джойстик виртуальным, он создаёт виртуальный джойстик параллельно. Поэтому фактически в системе два джойстика - реальный и виртуальный. На программном уровне скрыть реальный джойстик нельзя. Можно попробовать решения, вроде [HidHide](https://github.com/ViGEm/HidHide), которые используют специальные драйвера, есть вероятность, что поможет.

Mi-ViGEm doesn't replace original gamepad with virtual, it creates virtual gamepad in parallel. That's why both gamepads (original and virtual) are presented in OS. There is no way to hide original gamepad on user application level. As a workaround you can try [HidHide](https://github.com/ViGEm/HidHide) which uses kernel-level driver to hide original device.

**Comment by onuff** [comment]
Как туда зайти, чтобы hidhide настроить?

**Comment by grayver** [comment]
Установить HidHide драйвер, запустить HidHide-клиент. На вкладке Applications выбрать приложение Mi-ViGEm, на вкладке Devices выбрать геймпад Xiaomi, установить галочку "Enable device hiding", перезагрузить.

Install HidHide driver, run HidHide client. On the Applications tab select Mi-ViGEm application, on the Devices tab select Xiaomi gamepad, check the "Enable device hiding" mark, reboot.
